version: '3.6'
services:
  django:
    build: .
    environment:
      - DJANGO_PORT=8000
    ports:
      - "18000:8000"
    stdin_open: true
    tty: true
    restart: always
  postgresql:
    image: postgres:9.5.10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    restart: always
    ports:
      - "5432:5432"