version: '3.6'
services:
  django:
    build: .
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/superrentals/ember/node_modules
    environment:
      - DJANGO_PORT=8000
      - DATABASE_URL=postgres://root:password@postgresql/superrentals
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    restart: always
  postgresql:
    image: postgres:9.5.10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=superrentals
    restart: always
    ports:
      - "5432:5432"